# Generated by Django 3.0.5 on 2020-04-14 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('room_floor', models.IntegerField(default='1')),
                ('room_num', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('duration', models.IntegerField(default=2)),
                ('decription', models.TextField(default='Add description here ', max_length=1500)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Room')),
            ],
        ),
    ]
